# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lbth-geospatial',
                'doc_host': 'https://data-hamlets.github.io',
                'git_url': 'https://github.com/data-hamlets/lbth-geospatial',
                'lib_path': 'lbth_geospatial'},
  'syms': {'lbth_geospatial.core': {'lbth_geospatial.core.plot_wards': ('core.html#plot_wards', 'lbth_geospatial/core.py')}}}
